### ISSUE TITLE
Allow source code scanning

### ISSUE THREAD

**Issue by mmurto** [doubleopen-project/dos#1]
Users should be able to use DOS to scan the source code of packages on the server. Use [ScanCode](https://github.com/nexB/scancode-toolkit) as the scanner. Store the scan results in the database.

- [x] #37
- [x] #31
- [x] #39
- [x] #40
- [x] #41

**Comment by Etsija** [comment]
https://drive.google.com/file/d/19V1Dh-mbUuDdAEmNpLjipLpdKbC_d1tV/view?usp=share_link

**Comment by Etsija** [comment]
https://viewer.diagrams.net/index.html?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=DOS%20scanning.drawio#R7Vzfc6I6FP5rfNwZIID6WGvv7szdne6t3dnZRyqpchcJG4I%2F7l9%2FEw0qJ0CkglXrQ6dwCBCT75zvnC%2FRDrqfLT9TL55%2BIz4OO5bhLzto2LEs0zAd%2Fk9YVhuLa0jDhAa%2BbLQzjIL%2FcHantKaBj5NcQ0ZIyII4bxyTKMJjlrN5lJJFvtkrCfNvjb0JVgyjsReq1p%2BBz6Yba88xdvYvOJhMszebhrwy87LG0pBMPZ8s9kzooYPuKSFsczRb3uNQDF42Lpv7%2Fiq5uu0YxRE75AbvW5%2Bu5mg571rxH7L8Z%2Fj05eGTfMrcC1P5gTvo7keCqewzW2UDwbsfi8N0Fn4NXnEYRPxsEGMazDDj7dEwlObvO9tgMQ0YHsXeWNy64BDhtimbhfzM5Id81pjHbxG3G%2FzcpyR%2B9ugEM2kYkzD04iR4WXdDWCgepzQJ5vgJJxu0CCtJmXj1%2FRYFwhgTyrglYZS%2FQxixl7AFTvjhIMKLB5%2FPdPYBu4OO5f5JxWQM8PbC1sRHZe96%2BEL27t41su5Bo5IHzDFlAcdYya38A86xn7vXyDWgJI18pUV3uH4QREU2xfydeLlnkij5jAmfLLriTeRVWwJ2lT9d7OC%2FBfl0D%2Fp21tCTLjfZPnmHSn4ggVkDpJYKUojOPUzFhE%2F2ugvOoOMMAUg5JKZkQiIv3IdpIXzYGogjgftEBf4NW7qYcjjgnBzgukWAU%2FGGnLbwhhS8peuIaNA0Svi%2Fx6fnKgBmM3AXBpOI214IY2TGLyQcUexOkJIAIn%2B8mMrIzywvIRn%2FzppJJuzlIMNRlodHBgU03E77dopluJTTuTmrN4Msi8QaxxQdrJxnikOP8ZCdZ%2BeCaZO3fhcuvMPHJ7MYINkTEpLSMZY3gbnf9uLtcHCKOHL4OLpR5LWEsdoR6%2Fw40r1x5JmCqzKmvJUjewdyZGt46yp4%2B5PidYeTsRetY36ShhxjbyHKAlJslQSl%2F294RM93Wl50T8OLZj8PChMdRox8bL3VXjMZDcrf08tHOzNfafKDzRMbZd2eArCIiGmjeB6QNNlHGK%2Fq%2BfweizQS40jwq5dM11AxN5dPlYgdikH3vHIziEEr03eyR2w6ejQGt%2BEtw6AL1A7YLxe0dzTt%2B%2Fn2WYRtCuOO9xzTu6c0Hv5a%2Fpg89r7%2F9J8K1BeKeRhN2AboPk%2FfJpHgGSONQ%2BKJgx9PX882pAKsnSDGNg9nC8Cm305ItQwAN6MePLPz0vZdQA3dCjirvUPFvdM5dVN%2BUSD4oLsRUoB%2FK7guKCdWct2C%2BFCe%2Fr5nwVWIUVUkqorLt4LrXcFVHmXOseAq7K1dFBOHg1tMvGLYVsdE9%2BxiYoFSeouJ5wqu8ihzMTGxXITCyyBhQTS5HD2qkeKpQBwod9TGiycEipq29CjUK9a9DitubFhKwV62XNx8BGGrLpir2OSdlAAEBSe43NyQsGVbTuF7yip7BCt7u7q9bQCBrpYS4ECXhqPQ3NprIQb6irPsFLKrl8IOjeboJNF8y%2B0NR3MFoKbGARTFWdMerl5UKbtq77qaUWiZLbLX7XlAggUnNAH%2FS2UG9L7MADRiC%2Ba3DTEDBK6FajqGhhkQSOe1zwfMg9yjHAmOWstMYqqLLR%2FKkY5fTGx9scVqKcWyShy2fO3QKexXaXvoqLq1Sbi8ons%2BWMtEtRjMgo534hTOtBTH61huKBQLP5jzw4kUL0a8UI%2FW%2ByzvJgLJshF%2F6X476Kk3vfN6JKlqvbN3dnqneVsEuiB0VUSni1E8TXUZSO5N3%2BwQEaLRmPj42ITmvAtjS01bTlgYm0AZ2qKi6T0iYNs72JJUsKekUunRb3lyauXzcBS6h238aiytUHc8y3z%2B8eVfESot428shpsJdVUuAnj8j8fANezGvzG7bjc5VD8y2%2FETqB2itgQkgESkU0RB%2Bo006boL22vqZBf2RyNouXCcNIKW06uMCxq%2FdfuaWWnbb9VFu4iw4HW1zhV2Gx3HZBaHPAnyj%2FXRC6jNjxK52qnNoch1KExqi1xQVNKqv6Bf8FvPishVzxkRqJZtuxYp9t4W8hpzLnVxsXmHOm%2FSK8gNT7l%2FGMbylpbAYa6n4yS4TV%2FnNlDSApykk5ygYHXiJXZTXTb8%2FPDMDUSmhh%2BTUcwCSjlh3eTAvMhth1KU%2FEuT3zkQrRo51gEUZNfKv3pdzSi0TBEZr6t1U%2BYc%2BxXTlTDFoQnWScsjCNOWZAQXZnIaGUFxH42M4EBqqSUjdCFhwlFo%2B6smpcuCze4bvCbOOGE%2BBRNq%2B8BvItV1EghiW1eDA2EYab6P5YAyx6n6Cq2WM5RRaJszLNVJGKG4cS85G8I4y921AKJWO3xhm8XvOXSDoV23gu%2FXcQUbOiochbb5Ql2AkfKV6gvG2kmOrrcvlTrOa%2F%2BusgrcFHM4xe8przYAgHXVBnRH3fMBMzm19vu6rmbU2mYadVWHYpbS6CMmZBewZctua8sWJBXdFinohdqfhwDP162VQi%2FUPR96YS2Sg1u2lFF%2Bsxfy090vjm6a7363FT38Dw%3D%3D
