### ISSUE TITLE
Determine and intialize production environment

### ISSUE THREAD

**Issue by mmurto** [doubleopen-project/dos#10]
Where to host what?

**Comment by lamppu** [comment]
Heroku

- pricing starts from 5$ a month [https://www.heroku.com/pricing](https://www.heroku.com/pricing)
- the plan can be upgraded when needed
- you can deploy with Git and Docker
- you can also deploy a development branch of your application to a staging application on Heroku
- you can enable automatic deploys for a GitHub branch
- if you’ve configured your GitHub repo to use automated Continuous Integration, you can check the “Wait for CI to pass before deploy” checkbox. When enabled, Heroku will only auto-deploy after all the commit statuses of the relevant commit show success.
- each Heroku account can create up to 5 Teams. Each Team can have up to 25 members. Teams of up to 5 members are free. Larger teams are charged at $10 per month.
- An account can have no more than 100 apps.
- A single app can have up to 1,000 custom domains assigned to it.

**Comment by willebra** [comment]
Any European alternatives?

**Comment by lamppu** [comment]
European alternatives to Heroku
- [Scalingo](https://scalingo.com/)
- [platform.sh](https://platform.sh/)
- [Clever Cloud](https://www.clever-cloud.com)

European object storage option:
- [Scaleway Object Storage](https://www.scaleway.com/en/object-storage/)

**Comment by mmurto** [comment]
Frontend deployment:
- Vercel
- Netlify

**Comment by lamppu** [comment]
Starting with:
- Heroku
- Heroku Postgres
- Digital Open Spaces
- Vercel

These may change as the project advances and the requirements become clearer.

**Comment by lamppu** [comment]
- [x] create Heroku account
- [x] create Heroku app for dos
- [x] add PostgresSQL database to app
- [ ] create team and add team members
