### ISSUE TITLE
Setup initial development environment on Github

### ISSUE THREAD

**Issue by lamppu** [doubleopen-project/dos#13]
- [x] Add initial project structure
- [x] Add initial Turborepo configuration
- [x] Add Reuse action to GitHub workflows
- [x] Add initial license information
- [x] Add initial ESLint configuration
- [x] Add initial TypeScript configuration

What else?

**Comment by Etsija** [comment]
I think this issue can be closed now, as the initial dev environment is in use on GitHub.  Further development of the issue would be to include additional actions to Github workflows.
