### ISSUE TITLE
[DO-103] Improve package identification

### ISSUE THREAD

**Issue by lamppu** [doubleopen-project/dos#196]
It might be possible that a package can be downloaded from different sources, and might have slightly different contents. So we should possibly consider adding a check for the package hash as well.

<sub>From [SyncLinear.com](https://synclinear.com) | [DO-103](https://linear.app/double-open/issue/DO-103/improve-package-identification)</sub>

**Comment by Etsija** [comment]
We have concluded that purl is "good enough" source of truth for package identification, so this can be canceled.
