### ISSUE TITLE
[DO-282] No error message shown when submitting a path exclusion that is not accepted by the API

### ISSUE THREAD

**Issue by lamppu** [doubleopen-project/dos#500]
It would be nice if there was some sort of feedback shown to the user if the path exclusion doesn't get saved. Also perhaps the dialog could be closed only when the submit is successful, in case there is just a typo or something in the path exclusion pattern.

<sub>From [SyncLinear.com](https://synclinear.com) | [DO-282](https://linear.app/double-open/issue/DO-282/no-error-message-shown-when-submitting-a-path-exclusion-that-is-not)</sub>

**Comment by Etsija** [comment]
Any response got from DOS API in the failing case?
