### ISSUE TITLE
[DO-368] Refactor current sidebar

### ISSUE THREAD

**Issue by Etsija** [doubleopen-project/dos#624]
Replace the current sidebar implementation as the leftmost sub-panel of the Resizable, and make it also resizable (no collapse handling yet) and persisting with Zustand.

Effectively, after this sub-issue is done, we have a three-column resizable layout.

<sub>From [SyncLinear.com](https://synclinear.com) | [DO-368](https://linear.app/double-open/issue/DO-368/refactor-current-sidebar)</sub>

**Comment by lamppu** [comment]
Canceling this issue as a different approach regarding the sidebar has been chosen (will be turned into a top menu bar).
