### ISSUE TITLE
[DO-397] DOS should fail in ORT in case of too many "unsuccessful" responses

### ISSUE THREAD

**Issue by Etsija** [doubleopen-project/dos#665]
A mechanism should be implemented that tracks the number of "unsuccessful" responses received from the backend, and if too many, DOS should raise an exception and finish the run with an informative error message.

A typical reason for an unsuccessful response from backend is incorrect SERVER_TOKEN environment variable set (response: 403).  This will be a total failure of communication between the ORT client and DOS backend, so it is best to raise an exception immediately and stop the DOS Scanner / DOS Package Configuration Manager.

Because sometimes the client will also receive one or two "unsuccessful" responses from the backend in the middle of a very big scanning job, the DOS Scanner implementation should allow for some of these to be received, before the exception is raised.

<sub>From [SyncLinear.com](https://synclinear.com) | [DO-397](https://linear.app/double-open/issue/DO-397/dos-should-fail-in-ort-in-case-of-too-many-unsuccessful-responses)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [DO-397](https://linear.app/double-open/issue/DO-397/dos-should-fail-in-ort-in-case-of-too-many-unsuccessful-responses)</sub>

**Comment by sschuberth** [comment]
Duplicates https://github.com/doubleopen-project/dos/issues/589.
