### ISSUE TITLE
Enablement of GitHub Sponsors

### ISSUE THREAD

**Issue by schr3gl3j** [doubleopen-project/dos#784]
Could you please enable GitHub Sponsoring? 

Julian Schregle [julian.schregle@mercedes-benz.com](mailto:julian.schregle@mercedes-benz.com), Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/LEGAL_IMPRINT.md)

**Comment by sschuberth** [comment]
Hi @schr3gl3j, thanks for asking for this. Actually sponsoring @doubleopen-project has been enabled just recently, see https://github.com/sponsors/doubleopen-project 😺 Please let me know if this works for you!
